// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.21.1
// source: taoContext.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OrderType int32

const (
	OrderType_GTC        OrderType = 0
	OrderType_IOC        OrderType = 1
	OrderType_IOC_BUDGET OrderType = 2
	OrderType_FOK        OrderType = 3
	OrderType_FOK_BUDGET OrderType = 4
)

// Enum value maps for OrderType.
var (
	OrderType_name = map[int32]string{
		0: "GTC",
		1: "IOC",
		2: "IOC_BUDGET",
		3: "FOK",
		4: "FOK_BUDGET",
	}
	OrderType_value = map[string]int32{
		"GTC":        0,
		"IOC":        1,
		"IOC_BUDGET": 2,
		"FOK":        3,
		"FOK_BUDGET": 4,
	}
)

func (x OrderType) Enum() *OrderType {
	p := new(OrderType)
	*p = x
	return p
}

func (x OrderType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderType) Descriptor() protoreflect.EnumDescriptor {
	return file_taoContext_proto_enumTypes[0].Descriptor()
}

func (OrderType) Type() protoreflect.EnumType {
	return &file_taoContext_proto_enumTypes[0]
}

func (x OrderType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderType.Descriptor instead.
func (OrderType) EnumDescriptor() ([]byte, []int) {
	return file_taoContext_proto_rawDescGZIP(), []int{0}
}

type OrderSid int32

const (
	OrderSid_OFFER OrderSid = 0
	OrderSid_BID   OrderSid = 1
)

// Enum value maps for OrderSid.
var (
	OrderSid_name = map[int32]string{
		0: "OFFER",
		1: "BID",
	}
	OrderSid_value = map[string]int32{
		"OFFER": 0,
		"BID":   1,
	}
)

func (x OrderSid) Enum() *OrderSid {
	p := new(OrderSid)
	*p = x
	return p
}

func (x OrderSid) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderSid) Descriptor() protoreflect.EnumDescriptor {
	return file_taoContext_proto_enumTypes[1].Descriptor()
}

func (OrderSid) Type() protoreflect.EnumType {
	return &file_taoContext_proto_enumTypes[1]
}

func (x OrderSid) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderSid.Descriptor instead.
func (OrderSid) EnumDescriptor() ([]byte, []int) {
	return file_taoContext_proto_rawDescGZIP(), []int{1}
}

type OrderCmd int32

const (
	OrderCmd_PLACE  OrderCmd = 0
	OrderCmd_MOVE   OrderCmd = 1
	OrderCmd_CANCEL OrderCmd = 2
	OrderCmd_REDUCE OrderCmd = 3
	OrderCmd_REJECT OrderCmd = 4
	OrderCmd_ACCEPT OrderCmd = 5
)

// Enum value maps for OrderCmd.
var (
	OrderCmd_name = map[int32]string{
		0: "PLACE",
		1: "MOVE",
		2: "CANCEL",
		3: "REDUCE",
		4: "REJECT",
		5: "ACCEPT",
	}
	OrderCmd_value = map[string]int32{
		"PLACE":  0,
		"MOVE":   1,
		"CANCEL": 2,
		"REDUCE": 3,
		"REJECT": 4,
		"ACCEPT": 5,
	}
)

func (x OrderCmd) Enum() *OrderCmd {
	p := new(OrderCmd)
	*p = x
	return p
}

func (x OrderCmd) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderCmd) Descriptor() protoreflect.EnumDescriptor {
	return file_taoContext_proto_enumTypes[2].Descriptor()
}

func (OrderCmd) Type() protoreflect.EnumType {
	return &file_taoContext_proto_enumTypes[2]
}

func (x OrderCmd) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderCmd.Descriptor instead.
func (OrderCmd) EnumDescriptor() ([]byte, []int) {
	return file_taoContext_proto_rawDescGZIP(), []int{2}
}

type OrderDto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id              string    `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type            OrderType `protobuf:"varint,2,opt,name=type,proto3,enum=grpc.OrderType" json:"type,omitempty"`
	Side            OrderSid  `protobuf:"varint,3,opt,name=side,proto3,enum=grpc.OrderSid" json:"side,omitempty"`
	Commond         OrderCmd  `protobuf:"varint,4,opt,name=commond,proto3,enum=grpc.OrderCmd" json:"commond,omitempty"`
	Version         int32     `protobuf:"varint,5,opt,name=version,proto3" json:"version,omitempty"`
	Timestamp       int64     `protobuf:"varint,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Price           int64     `protobuf:"varint,7,opt,name=price,proto3" json:"price,omitempty"`
	ReserveBidPrice int64     `protobuf:"varint,8,opt,name=reserveBidPrice,proto3" json:"reserveBidPrice,omitempty"`
	Amount          int64     `protobuf:"varint,9,opt,name=amount,proto3" json:"amount,omitempty"`
	TakerFee        int64     `protobuf:"varint,11,opt,name=takerFee,proto3" json:"takerFee,omitempty"`
	MakerFee        int64     `protobuf:"varint,12,opt,name=makerFee,proto3" json:"makerFee,omitempty"`
	Market          string    `protobuf:"bytes,13,opt,name=market,proto3" json:"market,omitempty"`
	UserId          string    `protobuf:"bytes,14,opt,name=userId,proto3" json:"userId,omitempty"`
	Source          string    `protobuf:"bytes,15,opt,name=source,proto3" json:"source,omitempty"`
}

func (x *OrderDto) Reset() {
	*x = OrderDto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_taoContext_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrderDto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderDto) ProtoMessage() {}

func (x *OrderDto) ProtoReflect() protoreflect.Message {
	mi := &file_taoContext_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderDto.ProtoReflect.Descriptor instead.
func (*OrderDto) Descriptor() ([]byte, []int) {
	return file_taoContext_proto_rawDescGZIP(), []int{0}
}

func (x *OrderDto) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *OrderDto) GetType() OrderType {
	if x != nil {
		return x.Type
	}
	return OrderType_GTC
}

func (x *OrderDto) GetSide() OrderSid {
	if x != nil {
		return x.Side
	}
	return OrderSid_OFFER
}

func (x *OrderDto) GetCommond() OrderCmd {
	if x != nil {
		return x.Commond
	}
	return OrderCmd_PLACE
}

func (x *OrderDto) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *OrderDto) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *OrderDto) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *OrderDto) GetReserveBidPrice() int64 {
	if x != nil {
		return x.ReserveBidPrice
	}
	return 0
}

func (x *OrderDto) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *OrderDto) GetTakerFee() int64 {
	if x != nil {
		return x.TakerFee
	}
	return 0
}

func (x *OrderDto) GetMakerFee() int64 {
	if x != nil {
		return x.MakerFee
	}
	return 0
}

func (x *OrderDto) GetMarket() string {
	if x != nil {
		return x.Market
	}
	return ""
}

func (x *OrderDto) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *OrderDto) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

type OrderReplyDto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ReplyId string    `protobuf:"bytes,1,opt,name=replyId,proto3" json:"replyId,omitempty"`
	Order   *OrderDto `protobuf:"bytes,2,opt,name=order,proto3" json:"order,omitempty"`
	Commond OrderCmd  `protobuf:"varint,3,opt,name=commond,proto3,enum=grpc.OrderCmd" json:"commond,omitempty"`
	Filled  int64     `protobuf:"varint,4,opt,name=filled,proto3" json:"filled,omitempty"`
	Left    int64     `protobuf:"varint,5,opt,name=left,proto3" json:"left,omitempty"`
	Fee     int64     `protobuf:"varint,6,opt,name=fee,proto3" json:"fee,omitempty"`
}

func (x *OrderReplyDto) Reset() {
	*x = OrderReplyDto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_taoContext_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrderReplyDto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderReplyDto) ProtoMessage() {}

func (x *OrderReplyDto) ProtoReflect() protoreflect.Message {
	mi := &file_taoContext_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderReplyDto.ProtoReflect.Descriptor instead.
func (*OrderReplyDto) Descriptor() ([]byte, []int) {
	return file_taoContext_proto_rawDescGZIP(), []int{1}
}

func (x *OrderReplyDto) GetReplyId() string {
	if x != nil {
		return x.ReplyId
	}
	return ""
}

func (x *OrderReplyDto) GetOrder() *OrderDto {
	if x != nil {
		return x.Order
	}
	return nil
}

func (x *OrderReplyDto) GetCommond() OrderCmd {
	if x != nil {
		return x.Commond
	}
	return OrderCmd_PLACE
}

func (x *OrderReplyDto) GetFilled() int64 {
	if x != nil {
		return x.Filled
	}
	return 0
}

func (x *OrderReplyDto) GetLeft() int64 {
	if x != nil {
		return x.Left
	}
	return 0
}

func (x *OrderReplyDto) GetFee() int64 {
	if x != nil {
		return x.Fee
	}
	return 0
}

type MarketDto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Symbol     string `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Target     string `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	Money      string `protobuf:"bytes,3,opt,name=money,proto3" json:"money,omitempty"`
	TargetPrec int32  `protobuf:"varint,4,opt,name=targetPrec,proto3" json:"targetPrec,omitempty"`
	MoneyPrec  int32  `protobuf:"varint,5,opt,name=moneyPrec,proto3" json:"moneyPrec,omitempty"`
	FeePrec    int32  `protobuf:"varint,6,opt,name=feePrec,proto3" json:"feePrec,omitempty"`
	MinAmount  int64  `protobuf:"varint,7,opt,name=minAmount,proto3" json:"minAmount,omitempty"`
	MinBase    int64  `protobuf:"varint,8,opt,name=minBase,proto3" json:"minBase,omitempty"`
}

func (x *MarketDto) Reset() {
	*x = MarketDto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_taoContext_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MarketDto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarketDto) ProtoMessage() {}

func (x *MarketDto) ProtoReflect() protoreflect.Message {
	mi := &file_taoContext_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarketDto.ProtoReflect.Descriptor instead.
func (*MarketDto) Descriptor() ([]byte, []int) {
	return file_taoContext_proto_rawDescGZIP(), []int{2}
}

func (x *MarketDto) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *MarketDto) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *MarketDto) GetMoney() string {
	if x != nil {
		return x.Money
	}
	return ""
}

func (x *MarketDto) GetTargetPrec() int32 {
	if x != nil {
		return x.TargetPrec
	}
	return 0
}

func (x *MarketDto) GetMoneyPrec() int32 {
	if x != nil {
		return x.MoneyPrec
	}
	return 0
}

func (x *MarketDto) GetFeePrec() int32 {
	if x != nil {
		return x.FeePrec
	}
	return 0
}

func (x *MarketDto) GetMinAmount() int64 {
	if x != nil {
		return x.MinAmount
	}
	return 0
}

func (x *MarketDto) GetMinBase() int64 {
	if x != nil {
		return x.MinBase
	}
	return 0
}

type QueryReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId  string `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Market  string `protobuf:"bytes,2,opt,name=market,proto3" json:"market,omitempty"`
	OrderId string `protobuf:"bytes,3,opt,name=orderId,proto3" json:"orderId,omitempty"`
}

func (x *QueryReq) Reset() {
	*x = QueryReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_taoContext_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryReq) ProtoMessage() {}

func (x *QueryReq) ProtoReflect() protoreflect.Message {
	mi := &file_taoContext_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryReq.ProtoReflect.Descriptor instead.
func (*QueryReq) Descriptor() ([]byte, []int) {
	return file_taoContext_proto_rawDescGZIP(), []int{3}
}

func (x *QueryReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *QueryReq) GetMarket() string {
	if x != nil {
		return x.Market
	}
	return ""
}

func (x *QueryReq) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

type QueryRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status    int32       `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Msg       string      `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	OrderList []*OrderDto `protobuf:"bytes,3,rep,name=orderList,proto3" json:"orderList,omitempty"`
}

func (x *QueryRsp) Reset() {
	*x = QueryRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_taoContext_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryRsp) ProtoMessage() {}

func (x *QueryRsp) ProtoReflect() protoreflect.Message {
	mi := &file_taoContext_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryRsp.ProtoReflect.Descriptor instead.
func (*QueryRsp) Descriptor() ([]byte, []int) {
	return file_taoContext_proto_rawDescGZIP(), []int{4}
}

func (x *QueryRsp) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *QueryRsp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *QueryRsp) GetOrderList() []*OrderDto {
	if x != nil {
		return x.OrderList
	}
	return nil
}

type OrderReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId string    `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Market string    `protobuf:"bytes,2,opt,name=market,proto3" json:"market,omitempty"`
	Order  *OrderDto `protobuf:"bytes,3,opt,name=order,proto3" json:"order,omitempty"`
}

func (x *OrderReq) Reset() {
	*x = OrderReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_taoContext_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrderReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderReq) ProtoMessage() {}

func (x *OrderReq) ProtoReflect() protoreflect.Message {
	mi := &file_taoContext_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderReq.ProtoReflect.Descriptor instead.
func (*OrderReq) Descriptor() ([]byte, []int) {
	return file_taoContext_proto_rawDescGZIP(), []int{5}
}

func (x *OrderReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *OrderReq) GetMarket() string {
	if x != nil {
		return x.Market
	}
	return ""
}

func (x *OrderReq) GetOrder() *OrderDto {
	if x != nil {
		return x.Order
	}
	return nil
}

type OrderRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status int32          `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Msg    string         `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Order  *OrderReplyDto `protobuf:"bytes,3,opt,name=order,proto3" json:"order,omitempty"`
}

func (x *OrderRsp) Reset() {
	*x = OrderRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_taoContext_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrderRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderRsp) ProtoMessage() {}

func (x *OrderRsp) ProtoReflect() protoreflect.Message {
	mi := &file_taoContext_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderRsp.ProtoReflect.Descriptor instead.
func (*OrderRsp) Descriptor() ([]byte, []int) {
	return file_taoContext_proto_rawDescGZIP(), []int{6}
}

func (x *OrderRsp) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *OrderRsp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *OrderRsp) GetOrder() *OrderReplyDto {
	if x != nil {
		return x.Order
	}
	return nil
}

var File_taoContext_proto protoreflect.FileDescriptor

var file_taoContext_proto_rawDesc = []byte{
	0x0a, 0x10, 0x74, 0x61, 0x6f, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x04, 0x67, 0x72, 0x70, 0x63, 0x22, 0x9d, 0x03, 0x0a, 0x08, 0x4f, 0x72, 0x64,
	0x65, 0x72, 0x44, 0x74, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x23, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x0f, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72,
	0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x22, 0x0a, 0x04, 0x73, 0x69,
	0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0e, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e,
	0x4f, 0x72, 0x64, 0x65, 0x72, 0x53, 0x69, 0x64, 0x52, 0x04, 0x73, 0x69, 0x64, 0x65, 0x12, 0x28,
	0x0a, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x0e, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x43, 0x6d, 0x64, 0x52,
	0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73,
	0x69, 0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69,
	0x6f, 0x6e, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x12, 0x28, 0x0a, 0x0f, 0x72, 0x65, 0x73, 0x65, 0x72, 0x76,
	0x65, 0x42, 0x69, 0x64, 0x50, 0x72, 0x69, 0x63, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x0f, 0x72, 0x65, 0x73, 0x65, 0x72, 0x76, 0x65, 0x42, 0x69, 0x64, 0x50, 0x72, 0x69, 0x63, 0x65,
	0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x09, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x74, 0x61, 0x6b, 0x65,
	0x72, 0x46, 0x65, 0x65, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x74, 0x61, 0x6b, 0x65,
	0x72, 0x46, 0x65, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x6d, 0x61, 0x6b, 0x65, 0x72, 0x46, 0x65, 0x65,
	0x18, 0x0c, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x6d, 0x61, 0x6b, 0x65, 0x72, 0x46, 0x65, 0x65,
	0x12, 0x16, 0x0a, 0x06, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72,
	0x49, 0x64, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64,
	0x12, 0x16, 0x0a, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x18, 0x0f, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x22, 0xb7, 0x01, 0x0a, 0x0d, 0x4f, 0x72, 0x64,
	0x65, 0x72, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x44, 0x74, 0x6f, 0x12, 0x18, 0x0a, 0x07, 0x72, 0x65,
	0x70, 0x6c, 0x79, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x72, 0x65, 0x70,
	0x6c, 0x79, 0x49, 0x64, 0x12, 0x24, 0x0a, 0x05, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72,
	0x44, 0x74, 0x6f, 0x52, 0x05, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x12, 0x28, 0x0a, 0x07, 0x63, 0x6f,
	0x6d, 0x6d, 0x6f, 0x6e, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0e, 0x2e, 0x67, 0x72,
	0x70, 0x63, 0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x43, 0x6d, 0x64, 0x52, 0x07, 0x63, 0x6f, 0x6d,
	0x6d, 0x6f, 0x6e, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x66, 0x69, 0x6c, 0x6c, 0x65, 0x64, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x66, 0x69, 0x6c, 0x6c, 0x65, 0x64, 0x12, 0x12, 0x0a, 0x04,
	0x6c, 0x65, 0x66, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x6c, 0x65, 0x66, 0x74,
	0x12, 0x10, 0x0a, 0x03, 0x66, 0x65, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x66,
	0x65, 0x65, 0x22, 0xe1, 0x01, 0x0a, 0x09, 0x4d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x44, 0x74, 0x6f,
	0x12, 0x16, 0x0a, 0x06, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x61, 0x72, 0x67,
	0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74,
	0x12, 0x14, 0x0a, 0x05, 0x6d, 0x6f, 0x6e, 0x65, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x6d, 0x6f, 0x6e, 0x65, 0x79, 0x12, 0x1e, 0x0a, 0x0a, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74,
	0x50, 0x72, 0x65, 0x63, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x74, 0x61, 0x72, 0x67,
	0x65, 0x74, 0x50, 0x72, 0x65, 0x63, 0x12, 0x1c, 0x0a, 0x09, 0x6d, 0x6f, 0x6e, 0x65, 0x79, 0x50,
	0x72, 0x65, 0x63, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x6d, 0x6f, 0x6e, 0x65, 0x79,
	0x50, 0x72, 0x65, 0x63, 0x12, 0x18, 0x0a, 0x07, 0x66, 0x65, 0x65, 0x50, 0x72, 0x65, 0x63, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x66, 0x65, 0x65, 0x50, 0x72, 0x65, 0x63, 0x12, 0x1c,
	0x0a, 0x09, 0x6d, 0x69, 0x6e, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x09, 0x6d, 0x69, 0x6e, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x18, 0x0a, 0x07,
	0x6d, 0x69, 0x6e, 0x42, 0x61, 0x73, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x6d,
	0x69, 0x6e, 0x42, 0x61, 0x73, 0x65, 0x22, 0x54, 0x0a, 0x08, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52,
	0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x61,
	0x72, 0x6b, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6d, 0x61, 0x72, 0x6b,
	0x65, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x64, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x64, 0x22, 0x62, 0x0a, 0x08,
	0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x73, 0x70, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d,
	0x73, 0x67, 0x12, 0x2c, 0x0a, 0x09, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x18,
	0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x4f, 0x72, 0x64,
	0x65, 0x72, 0x44, 0x74, 0x6f, 0x52, 0x09, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74,
	0x22, 0x60, 0x0a, 0x08, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06,
	0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73,
	0x65, 0x72, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x12, 0x24, 0x0a, 0x05,
	0x6f, 0x72, 0x64, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x67, 0x72,
	0x70, 0x63, 0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x44, 0x74, 0x6f, 0x52, 0x05, 0x6f, 0x72, 0x64,
	0x65, 0x72, 0x22, 0x5f, 0x0a, 0x08, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x73, 0x70, 0x12, 0x16,
	0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x12, 0x29, 0x0a, 0x05, 0x6f, 0x72, 0x64, 0x65,
	0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x4f,
	0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x44, 0x74, 0x6f, 0x52, 0x05, 0x6f, 0x72,
	0x64, 0x65, 0x72, 0x2a, 0x46, 0x0a, 0x09, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x07, 0x0a, 0x03, 0x47, 0x54, 0x43, 0x10, 0x00, 0x12, 0x07, 0x0a, 0x03, 0x49, 0x4f, 0x43,
	0x10, 0x01, 0x12, 0x0e, 0x0a, 0x0a, 0x49, 0x4f, 0x43, 0x5f, 0x42, 0x55, 0x44, 0x47, 0x45, 0x54,
	0x10, 0x02, 0x12, 0x07, 0x0a, 0x03, 0x46, 0x4f, 0x4b, 0x10, 0x03, 0x12, 0x0e, 0x0a, 0x0a, 0x46,
	0x4f, 0x4b, 0x5f, 0x42, 0x55, 0x44, 0x47, 0x45, 0x54, 0x10, 0x04, 0x2a, 0x1e, 0x0a, 0x08, 0x4f,
	0x72, 0x64, 0x65, 0x72, 0x53, 0x69, 0x64, 0x12, 0x09, 0x0a, 0x05, 0x4f, 0x46, 0x46, 0x45, 0x52,
	0x10, 0x00, 0x12, 0x07, 0x0a, 0x03, 0x42, 0x49, 0x44, 0x10, 0x01, 0x2a, 0x4f, 0x0a, 0x08, 0x4f,
	0x72, 0x64, 0x65, 0x72, 0x43, 0x6d, 0x64, 0x12, 0x09, 0x0a, 0x05, 0x50, 0x4c, 0x41, 0x43, 0x45,
	0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x4d, 0x4f, 0x56, 0x45, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06,
	0x43, 0x41, 0x4e, 0x43, 0x45, 0x4c, 0x10, 0x02, 0x12, 0x0a, 0x0a, 0x06, 0x52, 0x45, 0x44, 0x55,
	0x43, 0x45, 0x10, 0x03, 0x12, 0x0a, 0x0a, 0x06, 0x52, 0x45, 0x4a, 0x45, 0x43, 0x54, 0x10, 0x04,
	0x12, 0x0a, 0x0a, 0x06, 0x41, 0x43, 0x43, 0x45, 0x50, 0x54, 0x10, 0x05, 0x42, 0x07, 0x5a, 0x05,
	0x2f, 0x67, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_taoContext_proto_rawDescOnce sync.Once
	file_taoContext_proto_rawDescData = file_taoContext_proto_rawDesc
)

func file_taoContext_proto_rawDescGZIP() []byte {
	file_taoContext_proto_rawDescOnce.Do(func() {
		file_taoContext_proto_rawDescData = protoimpl.X.CompressGZIP(file_taoContext_proto_rawDescData)
	})
	return file_taoContext_proto_rawDescData
}

var file_taoContext_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_taoContext_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_taoContext_proto_goTypes = []interface{}{
	(OrderType)(0),        // 0: grpc.OrderType
	(OrderSid)(0),         // 1: grpc.OrderSid
	(OrderCmd)(0),         // 2: grpc.OrderCmd
	(*OrderDto)(nil),      // 3: grpc.OrderDto
	(*OrderReplyDto)(nil), // 4: grpc.OrderReplyDto
	(*MarketDto)(nil),     // 5: grpc.MarketDto
	(*QueryReq)(nil),      // 6: grpc.QueryReq
	(*QueryRsp)(nil),      // 7: grpc.QueryRsp
	(*OrderReq)(nil),      // 8: grpc.OrderReq
	(*OrderRsp)(nil),      // 9: grpc.OrderRsp
}
var file_taoContext_proto_depIdxs = []int32{
	0, // 0: grpc.OrderDto.type:type_name -> grpc.OrderType
	1, // 1: grpc.OrderDto.side:type_name -> grpc.OrderSid
	2, // 2: grpc.OrderDto.commond:type_name -> grpc.OrderCmd
	3, // 3: grpc.OrderReplyDto.order:type_name -> grpc.OrderDto
	2, // 4: grpc.OrderReplyDto.commond:type_name -> grpc.OrderCmd
	3, // 5: grpc.QueryRsp.orderList:type_name -> grpc.OrderDto
	3, // 6: grpc.OrderReq.order:type_name -> grpc.OrderDto
	4, // 7: grpc.OrderRsp.order:type_name -> grpc.OrderReplyDto
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_taoContext_proto_init() }
func file_taoContext_proto_init() {
	if File_taoContext_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_taoContext_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrderDto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_taoContext_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrderReplyDto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_taoContext_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MarketDto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_taoContext_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_taoContext_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_taoContext_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrderReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_taoContext_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrderRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_taoContext_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_taoContext_proto_goTypes,
		DependencyIndexes: file_taoContext_proto_depIdxs,
		EnumInfos:         file_taoContext_proto_enumTypes,
		MessageInfos:      file_taoContext_proto_msgTypes,
	}.Build()
	File_taoContext_proto = out.File
	file_taoContext_proto_rawDesc = nil
	file_taoContext_proto_goTypes = nil
	file_taoContext_proto_depIdxs = nil
}
