// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.21.1
// source: taoContext.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OrderType int32

const (
	OrderType_OT_GTC        OrderType = 0
	OrderType_OT_IOC        OrderType = 1
	OrderType_OT_IOC_BUDGET OrderType = 2
	OrderType_OT_FOK        OrderType = 3
	OrderType_OT_FOK_BUDGET OrderType = 4
	OrderType_OT_UNKNOW     OrderType = 5
)

// Enum value maps for OrderType.
var (
	OrderType_name = map[int32]string{
		0: "OT_GTC",
		1: "OT_IOC",
		2: "OT_IOC_BUDGET",
		3: "OT_FOK",
		4: "OT_FOK_BUDGET",
		5: "OT_UNKNOW",
	}
	OrderType_value = map[string]int32{
		"OT_GTC":        0,
		"OT_IOC":        1,
		"OT_IOC_BUDGET": 2,
		"OT_FOK":        3,
		"OT_FOK_BUDGET": 4,
		"OT_UNKNOW":     5,
	}
)

func (x OrderType) Enum() *OrderType {
	p := new(OrderType)
	*p = x
	return p
}

func (x OrderType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderType) Descriptor() protoreflect.EnumDescriptor {
	return file_taoContext_proto_enumTypes[0].Descriptor()
}

func (OrderType) Type() protoreflect.EnumType {
	return &file_taoContext_proto_enumTypes[0]
}

func (x OrderType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderType.Descriptor instead.
func (OrderType) EnumDescriptor() ([]byte, []int) {
	return file_taoContext_proto_rawDescGZIP(), []int{0}
}

type OrderSid int32

const (
	OrderSid_SD_OFFER  OrderSid = 0
	OrderSid_SD_BID    OrderSid = 1
	OrderSid_SD_UNKNOW OrderSid = 2
)

// Enum value maps for OrderSid.
var (
	OrderSid_name = map[int32]string{
		0: "SD_OFFER",
		1: "SD_BID",
		2: "SD_UNKNOW",
	}
	OrderSid_value = map[string]int32{
		"SD_OFFER":  0,
		"SD_BID":    1,
		"SD_UNKNOW": 2,
	}
)

func (x OrderSid) Enum() *OrderSid {
	p := new(OrderSid)
	*p = x
	return p
}

func (x OrderSid) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderSid) Descriptor() protoreflect.EnumDescriptor {
	return file_taoContext_proto_enumTypes[1].Descriptor()
}

func (OrderSid) Type() protoreflect.EnumType {
	return &file_taoContext_proto_enumTypes[1]
}

func (x OrderSid) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderSid.Descriptor instead.
func (OrderSid) EnumDescriptor() ([]byte, []int) {
	return file_taoContext_proto_rawDescGZIP(), []int{1}
}

type OrderCmd int32

const (
	OrderCmd_CMD_PLACE  OrderCmd = 0
	OrderCmd_CMD_MOVE   OrderCmd = 1
	OrderCmd_CMD_CANCEL OrderCmd = 2
	OrderCmd_CMD_REDUCE OrderCmd = 3
	OrderCmd_CMD_UNKNOW OrderCmd = 4
)

// Enum value maps for OrderCmd.
var (
	OrderCmd_name = map[int32]string{
		0: "CMD_PLACE",
		1: "CMD_MOVE",
		2: "CMD_CANCEL",
		3: "CMD_REDUCE",
		4: "CMD_UNKNOW",
	}
	OrderCmd_value = map[string]int32{
		"CMD_PLACE":  0,
		"CMD_MOVE":   1,
		"CMD_CANCEL": 2,
		"CMD_REDUCE": 3,
		"CMD_UNKNOW": 4,
	}
)

func (x OrderCmd) Enum() *OrderCmd {
	p := new(OrderCmd)
	*p = x
	return p
}

func (x OrderCmd) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderCmd) Descriptor() protoreflect.EnumDescriptor {
	return file_taoContext_proto_enumTypes[2].Descriptor()
}

func (OrderCmd) Type() protoreflect.EnumType {
	return &file_taoContext_proto_enumTypes[2]
}

func (x OrderCmd) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderCmd.Descriptor instead.
func (OrderCmd) EnumDescriptor() ([]byte, []int) {
	return file_taoContext_proto_rawDescGZIP(), []int{2}
}

type OrderStatus int32

const (
	OrderStatus_ST_INITIAL OrderStatus = 0
	OrderStatus_ST_ACCEPT  OrderStatus = 1
	OrderStatus_ST_REJECT  OrderStatus = 2
	OrderStatus_ST_CANCEL  OrderStatus = 3
	OrderStatus_ST_FINISH  OrderStatus = 4
	OrderStatus_ST_UNKNOW  OrderStatus = 5
)

// Enum value maps for OrderStatus.
var (
	OrderStatus_name = map[int32]string{
		0: "ST_INITIAL",
		1: "ST_ACCEPT",
		2: "ST_REJECT",
		3: "ST_CANCEL",
		4: "ST_FINISH",
		5: "ST_UNKNOW",
	}
	OrderStatus_value = map[string]int32{
		"ST_INITIAL": 0,
		"ST_ACCEPT":  1,
		"ST_REJECT":  2,
		"ST_CANCEL":  3,
		"ST_FINISH":  4,
		"ST_UNKNOW":  5,
	}
)

func (x OrderStatus) Enum() *OrderStatus {
	p := new(OrderStatus)
	*p = x
	return p
}

func (x OrderStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_taoContext_proto_enumTypes[3].Descriptor()
}

func (OrderStatus) Type() protoreflect.EnumType {
	return &file_taoContext_proto_enumTypes[3]
}

func (x OrderStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderStatus.Descriptor instead.
func (OrderStatus) EnumDescriptor() ([]byte, []int) {
	return file_taoContext_proto_rawDescGZIP(), []int{3}
}

type ShardRole int32

const (
	ShardRole_ROLE_MARKET ShardRole = 0
	ShardRole_ROLE_STORE  ShardRole = 1
)

// Enum value maps for ShardRole.
var (
	ShardRole_name = map[int32]string{
		0: "ROLE_MARKET",
		1: "ROLE_STORE",
	}
	ShardRole_value = map[string]int32{
		"ROLE_MARKET": 0,
		"ROLE_STORE":  1,
	}
)

func (x ShardRole) Enum() *ShardRole {
	p := new(ShardRole)
	*p = x
	return p
}

func (x ShardRole) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ShardRole) Descriptor() protoreflect.EnumDescriptor {
	return file_taoContext_proto_enumTypes[4].Descriptor()
}

func (ShardRole) Type() protoreflect.EnumType {
	return &file_taoContext_proto_enumTypes[4]
}

func (x ShardRole) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ShardRole.Descriptor instead.
func (ShardRole) EnumDescriptor() ([]byte, []int) {
	return file_taoContext_proto_rawDescGZIP(), []int{4}
}

type OrderDto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id              string      `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type            OrderType   `protobuf:"varint,2,opt,name=type,proto3,enum=grpc.OrderType" json:"type,omitempty"`
	Side            OrderSid    `protobuf:"varint,3,opt,name=side,proto3,enum=grpc.OrderSid" json:"side,omitempty"`
	Status          OrderStatus `protobuf:"varint,4,opt,name=status,proto3,enum=grpc.OrderStatus" json:"status,omitempty"`
	Version         int32       `protobuf:"varint,5,opt,name=version,proto3" json:"version,omitempty"`
	Timestamp       int64       `protobuf:"varint,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Price           int64       `protobuf:"varint,7,opt,name=price,proto3" json:"price,omitempty"`
	ReserveBidPrice int64       `protobuf:"varint,8,opt,name=reserveBidPrice,proto3" json:"reserveBidPrice,omitempty"`
	Amount          int64       `protobuf:"varint,9,opt,name=amount,proto3" json:"amount,omitempty"`
	Filled          int64       `protobuf:"varint,10,opt,name=filled,proto3" json:"filled,omitempty"`
	TakerFee        int64       `protobuf:"varint,11,opt,name=takerFee,proto3" json:"takerFee,omitempty"`
	MakerFee        int64       `protobuf:"varint,12,opt,name=makerFee,proto3" json:"makerFee,omitempty"`
	Fee             int64       `protobuf:"varint,13,opt,name=fee,proto3" json:"fee,omitempty"`
	Market          string      `protobuf:"bytes,14,opt,name=market,proto3" json:"market,omitempty"`
	UserId          string      `protobuf:"bytes,15,opt,name=userId,proto3" json:"userId,omitempty"`
	Source          string      `protobuf:"bytes,16,opt,name=source,proto3" json:"source,omitempty"`
}

func (x *OrderDto) Reset() {
	*x = OrderDto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_taoContext_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrderDto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderDto) ProtoMessage() {}

func (x *OrderDto) ProtoReflect() protoreflect.Message {
	mi := &file_taoContext_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderDto.ProtoReflect.Descriptor instead.
func (*OrderDto) Descriptor() ([]byte, []int) {
	return file_taoContext_proto_rawDescGZIP(), []int{0}
}

func (x *OrderDto) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *OrderDto) GetType() OrderType {
	if x != nil {
		return x.Type
	}
	return OrderType_OT_GTC
}

func (x *OrderDto) GetSide() OrderSid {
	if x != nil {
		return x.Side
	}
	return OrderSid_SD_OFFER
}

func (x *OrderDto) GetStatus() OrderStatus {
	if x != nil {
		return x.Status
	}
	return OrderStatus_ST_INITIAL
}

func (x *OrderDto) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *OrderDto) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *OrderDto) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *OrderDto) GetReserveBidPrice() int64 {
	if x != nil {
		return x.ReserveBidPrice
	}
	return 0
}

func (x *OrderDto) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *OrderDto) GetFilled() int64 {
	if x != nil {
		return x.Filled
	}
	return 0
}

func (x *OrderDto) GetTakerFee() int64 {
	if x != nil {
		return x.TakerFee
	}
	return 0
}

func (x *OrderDto) GetMakerFee() int64 {
	if x != nil {
		return x.MakerFee
	}
	return 0
}

func (x *OrderDto) GetFee() int64 {
	if x != nil {
		return x.Fee
	}
	return 0
}

func (x *OrderDto) GetMarket() string {
	if x != nil {
		return x.Market
	}
	return ""
}

func (x *OrderDto) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *OrderDto) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

type OrderReplyDto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ReplyId string    `protobuf:"bytes,1,opt,name=replyId,proto3" json:"replyId,omitempty"`
	Order   *OrderDto `protobuf:"bytes,2,opt,name=order,proto3" json:"order,omitempty"`
}

func (x *OrderReplyDto) Reset() {
	*x = OrderReplyDto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_taoContext_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrderReplyDto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderReplyDto) ProtoMessage() {}

func (x *OrderReplyDto) ProtoReflect() protoreflect.Message {
	mi := &file_taoContext_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderReplyDto.ProtoReflect.Descriptor instead.
func (*OrderReplyDto) Descriptor() ([]byte, []int) {
	return file_taoContext_proto_rawDescGZIP(), []int{1}
}

func (x *OrderReplyDto) GetReplyId() string {
	if x != nil {
		return x.ReplyId
	}
	return ""
}

func (x *OrderReplyDto) GetOrder() *OrderDto {
	if x != nil {
		return x.Order
	}
	return nil
}

type MarketDto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Symbol     string `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Target     string `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	Money      string `protobuf:"bytes,3,opt,name=money,proto3" json:"money,omitempty"`
	TargetPrec int32  `protobuf:"varint,4,opt,name=targetPrec,proto3" json:"targetPrec,omitempty"`
	MoneyPrec  int32  `protobuf:"varint,5,opt,name=moneyPrec,proto3" json:"moneyPrec,omitempty"`
	FeePrec    int32  `protobuf:"varint,6,opt,name=feePrec,proto3" json:"feePrec,omitempty"`
	MinAmount  int64  `protobuf:"varint,7,opt,name=minAmount,proto3" json:"minAmount,omitempty"`
	MinBase    int64  `protobuf:"varint,8,opt,name=minBase,proto3" json:"minBase,omitempty"`
}

func (x *MarketDto) Reset() {
	*x = MarketDto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_taoContext_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MarketDto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarketDto) ProtoMessage() {}

func (x *MarketDto) ProtoReflect() protoreflect.Message {
	mi := &file_taoContext_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarketDto.ProtoReflect.Descriptor instead.
func (*MarketDto) Descriptor() ([]byte, []int) {
	return file_taoContext_proto_rawDescGZIP(), []int{2}
}

func (x *MarketDto) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *MarketDto) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *MarketDto) GetMoney() string {
	if x != nil {
		return x.Money
	}
	return ""
}

func (x *MarketDto) GetTargetPrec() int32 {
	if x != nil {
		return x.TargetPrec
	}
	return 0
}

func (x *MarketDto) GetMoneyPrec() int32 {
	if x != nil {
		return x.MoneyPrec
	}
	return 0
}

func (x *MarketDto) GetFeePrec() int32 {
	if x != nil {
		return x.FeePrec
	}
	return 0
}

func (x *MarketDto) GetMinAmount() int64 {
	if x != nil {
		return x.MinAmount
	}
	return 0
}

func (x *MarketDto) GetMinBase() int64 {
	if x != nil {
		return x.MinBase
	}
	return 0
}

type QueryReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId  string `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Market  string `protobuf:"bytes,2,opt,name=market,proto3" json:"market,omitempty"`
	OrderId string `protobuf:"bytes,3,opt,name=orderId,proto3" json:"orderId,omitempty"`
}

func (x *QueryReq) Reset() {
	*x = QueryReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_taoContext_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryReq) ProtoMessage() {}

func (x *QueryReq) ProtoReflect() protoreflect.Message {
	mi := &file_taoContext_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryReq.ProtoReflect.Descriptor instead.
func (*QueryReq) Descriptor() ([]byte, []int) {
	return file_taoContext_proto_rawDescGZIP(), []int{3}
}

func (x *QueryReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *QueryReq) GetMarket() string {
	if x != nil {
		return x.Market
	}
	return ""
}

func (x *QueryReq) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

type QueryRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status    int32       `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Msg       string      `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	OrderList []*OrderDto `protobuf:"bytes,3,rep,name=orderList,proto3" json:"orderList,omitempty"`
}

func (x *QueryRsp) Reset() {
	*x = QueryRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_taoContext_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryRsp) ProtoMessage() {}

func (x *QueryRsp) ProtoReflect() protoreflect.Message {
	mi := &file_taoContext_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryRsp.ProtoReflect.Descriptor instead.
func (*QueryRsp) Descriptor() ([]byte, []int) {
	return file_taoContext_proto_rawDescGZIP(), []int{4}
}

func (x *QueryRsp) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *QueryRsp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *QueryRsp) GetOrderList() []*OrderDto {
	if x != nil {
		return x.OrderList
	}
	return nil
}

type OrderReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId string    `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Market string    `protobuf:"bytes,2,opt,name=market,proto3" json:"market,omitempty"`
	Order  *OrderDto `protobuf:"bytes,3,opt,name=order,proto3" json:"order,omitempty"`
	Cmd    OrderCmd  `protobuf:"varint,4,opt,name=cmd,proto3,enum=grpc.OrderCmd" json:"cmd,omitempty"`
}

func (x *OrderReq) Reset() {
	*x = OrderReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_taoContext_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrderReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderReq) ProtoMessage() {}

func (x *OrderReq) ProtoReflect() protoreflect.Message {
	mi := &file_taoContext_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderReq.ProtoReflect.Descriptor instead.
func (*OrderReq) Descriptor() ([]byte, []int) {
	return file_taoContext_proto_rawDescGZIP(), []int{5}
}

func (x *OrderReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *OrderReq) GetMarket() string {
	if x != nil {
		return x.Market
	}
	return ""
}

func (x *OrderReq) GetOrder() *OrderDto {
	if x != nil {
		return x.Order
	}
	return nil
}

func (x *OrderReq) GetCmd() OrderCmd {
	if x != nil {
		return x.Cmd
	}
	return OrderCmd_CMD_PLACE
}

type OrderRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status int32          `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Msg    string         `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Order  *OrderReplyDto `protobuf:"bytes,3,opt,name=order,proto3" json:"order,omitempty"`
}

func (x *OrderRsp) Reset() {
	*x = OrderRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_taoContext_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrderRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderRsp) ProtoMessage() {}

func (x *OrderRsp) ProtoReflect() protoreflect.Message {
	mi := &file_taoContext_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderRsp.ProtoReflect.Descriptor instead.
func (*OrderRsp) Descriptor() ([]byte, []int) {
	return file_taoContext_proto_rawDescGZIP(), []int{6}
}

func (x *OrderRsp) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *OrderRsp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *OrderRsp) GetOrder() *OrderReplyDto {
	if x != nil {
		return x.Order
	}
	return nil
}

type CommonReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MsgId string `protobuf:"bytes,1,opt,name=msgId,proto3" json:"msgId,omitempty"`
}

func (x *CommonReq) Reset() {
	*x = CommonReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_taoContext_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommonReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommonReq) ProtoMessage() {}

func (x *CommonReq) ProtoReflect() protoreflect.Message {
	mi := &file_taoContext_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommonReq.ProtoReflect.Descriptor instead.
func (*CommonReq) Descriptor() ([]byte, []int) {
	return file_taoContext_proto_rawDescGZIP(), []int{7}
}

func (x *CommonReq) GetMsgId() string {
	if x != nil {
		return x.MsgId
	}
	return ""
}

type CommonRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status int32  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Msg    string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *CommonRsp) Reset() {
	*x = CommonRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_taoContext_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommonRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommonRsp) ProtoMessage() {}

func (x *CommonRsp) ProtoReflect() protoreflect.Message {
	mi := &file_taoContext_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommonRsp.ProtoReflect.Descriptor instead.
func (*CommonRsp) Descriptor() ([]byte, []int) {
	return file_taoContext_proto_rawDescGZIP(), []int{8}
}

func (x *CommonRsp) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *CommonRsp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type BatchGetReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Offset int32  `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	Market string `protobuf:"bytes,2,opt,name=market,proto3" json:"market,omitempty"`
}

func (x *BatchGetReq) Reset() {
	*x = BatchGetReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_taoContext_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BatchGetReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGetReq) ProtoMessage() {}

func (x *BatchGetReq) ProtoReflect() protoreflect.Message {
	mi := &file_taoContext_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGetReq.ProtoReflect.Descriptor instead.
func (*BatchGetReq) Descriptor() ([]byte, []int) {
	return file_taoContext_proto_rawDescGZIP(), []int{9}
}

func (x *BatchGetReq) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *BatchGetReq) GetMarket() string {
	if x != nil {
		return x.Market
	}
	return ""
}

type BatchGetRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status    int32       `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Msg       string      `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	OrderList []*OrderDto `protobuf:"bytes,3,rep,name=orderList,proto3" json:"orderList,omitempty"`
}

func (x *BatchGetRsp) Reset() {
	*x = BatchGetRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_taoContext_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BatchGetRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGetRsp) ProtoMessage() {}

func (x *BatchGetRsp) ProtoReflect() protoreflect.Message {
	mi := &file_taoContext_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGetRsp.ProtoReflect.Descriptor instead.
func (*BatchGetRsp) Descriptor() ([]byte, []int) {
	return file_taoContext_proto_rawDescGZIP(), []int{10}
}

func (x *BatchGetRsp) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *BatchGetRsp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *BatchGetRsp) GetOrderList() []*OrderDto {
	if x != nil {
		return x.OrderList
	}
	return nil
}

type MarketShardDto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ShardId    string   `protobuf:"bytes,1,opt,name=shardId,proto3" json:"shardId,omitempty"`
	MarketList []string `protobuf:"bytes,2,rep,name=marketList,proto3" json:"marketList,omitempty"`
}

func (x *MarketShardDto) Reset() {
	*x = MarketShardDto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_taoContext_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MarketShardDto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarketShardDto) ProtoMessage() {}

func (x *MarketShardDto) ProtoReflect() protoreflect.Message {
	mi := &file_taoContext_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarketShardDto.ProtoReflect.Descriptor instead.
func (*MarketShardDto) Descriptor() ([]byte, []int) {
	return file_taoContext_proto_rawDescGZIP(), []int{11}
}

func (x *MarketShardDto) GetShardId() string {
	if x != nil {
		return x.ShardId
	}
	return ""
}

func (x *MarketShardDto) GetMarketList() []string {
	if x != nil {
		return x.MarketList
	}
	return nil
}

type ShardListRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status    int32    `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Msg       string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	ShardList []string `protobuf:"bytes,3,rep,name=shardList,proto3" json:"shardList,omitempty"`
}

func (x *ShardListRsp) Reset() {
	*x = ShardListRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_taoContext_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShardListRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShardListRsp) ProtoMessage() {}

func (x *ShardListRsp) ProtoReflect() protoreflect.Message {
	mi := &file_taoContext_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShardListRsp.ProtoReflect.Descriptor instead.
func (*ShardListRsp) Descriptor() ([]byte, []int) {
	return file_taoContext_proto_rawDescGZIP(), []int{12}
}

func (x *ShardListRsp) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *ShardListRsp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *ShardListRsp) GetShardList() []string {
	if x != nil {
		return x.ShardList
	}
	return nil
}

type ShardReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ShardId string    `protobuf:"bytes,1,opt,name=shardId,proto3" json:"shardId,omitempty"`
	AppId   string    `protobuf:"bytes,2,opt,name=appId,proto3" json:"appId,omitempty"`
	Ip      string    `protobuf:"bytes,3,opt,name=ip,proto3" json:"ip,omitempty"`
	Port    int32     `protobuf:"varint,4,opt,name=port,proto3" json:"port,omitempty"`
	Role    ShardRole `protobuf:"varint,5,opt,name=role,proto3,enum=grpc.ShardRole" json:"role,omitempty"`
}

func (x *ShardReq) Reset() {
	*x = ShardReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_taoContext_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShardReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShardReq) ProtoMessage() {}

func (x *ShardReq) ProtoReflect() protoreflect.Message {
	mi := &file_taoContext_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShardReq.ProtoReflect.Descriptor instead.
func (*ShardReq) Descriptor() ([]byte, []int) {
	return file_taoContext_proto_rawDescGZIP(), []int{13}
}

func (x *ShardReq) GetShardId() string {
	if x != nil {
		return x.ShardId
	}
	return ""
}

func (x *ShardReq) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *ShardReq) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *ShardReq) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *ShardReq) GetRole() ShardRole {
	if x != nil {
		return x.Role
	}
	return ShardRole_ROLE_MARKET
}

type LockShardRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status     int32           `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Msg        string          `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	MarketList *MarketShardDto `protobuf:"bytes,3,opt,name=marketList,proto3" json:"marketList,omitempty"`
}

func (x *LockShardRsp) Reset() {
	*x = LockShardRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_taoContext_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LockShardRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LockShardRsp) ProtoMessage() {}

func (x *LockShardRsp) ProtoReflect() protoreflect.Message {
	mi := &file_taoContext_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LockShardRsp.ProtoReflect.Descriptor instead.
func (*LockShardRsp) Descriptor() ([]byte, []int) {
	return file_taoContext_proto_rawDescGZIP(), []int{14}
}

func (x *LockShardRsp) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *LockShardRsp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *LockShardRsp) GetMarketList() *MarketShardDto {
	if x != nil {
		return x.MarketList
	}
	return nil
}

type ConnectorDto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ShardId string    `protobuf:"bytes,1,opt,name=shardId,proto3" json:"shardId,omitempty"`
	AppId   string    `protobuf:"bytes,2,opt,name=appId,proto3" json:"appId,omitempty"`
	Ip      string    `protobuf:"bytes,3,opt,name=ip,proto3" json:"ip,omitempty"`
	Port    int32     `protobuf:"varint,4,opt,name=port,proto3" json:"port,omitempty"`
	Status  int32     `protobuf:"varint,5,opt,name=status,proto3" json:"status,omitempty"`
	Role    ShardRole `protobuf:"varint,6,opt,name=role,proto3,enum=grpc.ShardRole" json:"role,omitempty"`
}

func (x *ConnectorDto) Reset() {
	*x = ConnectorDto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_taoContext_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConnectorDto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectorDto) ProtoMessage() {}

func (x *ConnectorDto) ProtoReflect() protoreflect.Message {
	mi := &file_taoContext_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectorDto.ProtoReflect.Descriptor instead.
func (*ConnectorDto) Descriptor() ([]byte, []int) {
	return file_taoContext_proto_rawDescGZIP(), []int{15}
}

func (x *ConnectorDto) GetShardId() string {
	if x != nil {
		return x.ShardId
	}
	return ""
}

func (x *ConnectorDto) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *ConnectorDto) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *ConnectorDto) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *ConnectorDto) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *ConnectorDto) GetRole() ShardRole {
	if x != nil {
		return x.Role
	}
	return ShardRole_ROLE_MARKET
}

type ListConnectorRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status        int32         `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Msg           string        `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	ConnectorList *ConnectorDto `protobuf:"bytes,3,opt,name=connectorList,proto3" json:"connectorList,omitempty"`
}

func (x *ListConnectorRsp) Reset() {
	*x = ListConnectorRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_taoContext_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListConnectorRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListConnectorRsp) ProtoMessage() {}

func (x *ListConnectorRsp) ProtoReflect() protoreflect.Message {
	mi := &file_taoContext_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListConnectorRsp.ProtoReflect.Descriptor instead.
func (*ListConnectorRsp) Descriptor() ([]byte, []int) {
	return file_taoContext_proto_rawDescGZIP(), []int{16}
}

func (x *ListConnectorRsp) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *ListConnectorRsp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *ListConnectorRsp) GetConnectorList() *ConnectorDto {
	if x != nil {
		return x.ConnectorList
	}
	return nil
}

var File_taoContext_proto protoreflect.FileDescriptor

var file_taoContext_proto_rawDesc = []byte{
	0x0a, 0x10, 0x74, 0x61, 0x6f, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x04, 0x67, 0x72, 0x70, 0x63, 0x22, 0xc8, 0x03, 0x0a, 0x08, 0x4f, 0x72, 0x64,
	0x65, 0x72, 0x44, 0x74, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x23, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x0f, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72,
	0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x22, 0x0a, 0x04, 0x73, 0x69,
	0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0e, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e,
	0x4f, 0x72, 0x64, 0x65, 0x72, 0x53, 0x69, 0x64, 0x52, 0x04, 0x73, 0x69, 0x64, 0x65, 0x12, 0x29,
	0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x11,
	0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72,
	0x73, 0x69, 0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73,
	0x69, 0x6f, 0x6e, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x12, 0x28, 0x0a, 0x0f, 0x72, 0x65, 0x73, 0x65, 0x72,
	0x76, 0x65, 0x42, 0x69, 0x64, 0x50, 0x72, 0x69, 0x63, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x0f, 0x72, 0x65, 0x73, 0x65, 0x72, 0x76, 0x65, 0x42, 0x69, 0x64, 0x50, 0x72, 0x69, 0x63,
	0x65, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x09, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x66, 0x69, 0x6c,
	0x6c, 0x65, 0x64, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x66, 0x69, 0x6c, 0x6c, 0x65,
	0x64, 0x12, 0x1a, 0x0a, 0x08, 0x74, 0x61, 0x6b, 0x65, 0x72, 0x46, 0x65, 0x65, 0x18, 0x0b, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x08, 0x74, 0x61, 0x6b, 0x65, 0x72, 0x46, 0x65, 0x65, 0x12, 0x1a, 0x0a,
	0x08, 0x6d, 0x61, 0x6b, 0x65, 0x72, 0x46, 0x65, 0x65, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x08, 0x6d, 0x61, 0x6b, 0x65, 0x72, 0x46, 0x65, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x66, 0x65, 0x65,
	0x18, 0x0d, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x66, 0x65, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x6d,
	0x61, 0x72, 0x6b, 0x65, 0x74, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6d, 0x61, 0x72,
	0x6b, 0x65, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x0f, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x73,
	0x6f, 0x75, 0x72, 0x63, 0x65, 0x18, 0x10, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x22, 0x4f, 0x0a, 0x0d, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x44, 0x74, 0x6f, 0x12, 0x18, 0x0a, 0x07, 0x72, 0x65, 0x70, 0x6c, 0x79, 0x49, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x72, 0x65, 0x70, 0x6c, 0x79, 0x49, 0x64, 0x12, 0x24,
	0x0a, 0x05, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e,
	0x67, 0x72, 0x70, 0x63, 0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x44, 0x74, 0x6f, 0x52, 0x05, 0x6f,
	0x72, 0x64, 0x65, 0x72, 0x22, 0xe1, 0x01, 0x0a, 0x09, 0x4d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x44,
	0x74, 0x6f, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x61,
	0x72, 0x67, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x61, 0x72, 0x67,
	0x65, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x6f, 0x6e, 0x65, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x6d, 0x6f, 0x6e, 0x65, 0x79, 0x12, 0x1e, 0x0a, 0x0a, 0x74, 0x61, 0x72, 0x67,
	0x65, 0x74, 0x50, 0x72, 0x65, 0x63, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x74, 0x61,
	0x72, 0x67, 0x65, 0x74, 0x50, 0x72, 0x65, 0x63, 0x12, 0x1c, 0x0a, 0x09, 0x6d, 0x6f, 0x6e, 0x65,
	0x79, 0x50, 0x72, 0x65, 0x63, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x6d, 0x6f, 0x6e,
	0x65, 0x79, 0x50, 0x72, 0x65, 0x63, 0x12, 0x18, 0x0a, 0x07, 0x66, 0x65, 0x65, 0x50, 0x72, 0x65,
	0x63, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x66, 0x65, 0x65, 0x50, 0x72, 0x65, 0x63,
	0x12, 0x1c, 0x0a, 0x09, 0x6d, 0x69, 0x6e, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x09, 0x6d, 0x69, 0x6e, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x18,
	0x0a, 0x07, 0x6d, 0x69, 0x6e, 0x42, 0x61, 0x73, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x07, 0x6d, 0x69, 0x6e, 0x42, 0x61, 0x73, 0x65, 0x22, 0x54, 0x0a, 0x08, 0x51, 0x75, 0x65, 0x72,
	0x79, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06,
	0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6d, 0x61,
	0x72, 0x6b, 0x65, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x64, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x64, 0x22, 0x62,
	0x0a, 0x08, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x73, 0x70, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x6d, 0x73, 0x67, 0x12, 0x2c, 0x0a, 0x09, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x4c, 0x69, 0x73,
	0x74, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x4f,
	0x72, 0x64, 0x65, 0x72, 0x44, 0x74, 0x6f, 0x52, 0x09, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x4c, 0x69,
	0x73, 0x74, 0x22, 0x82, 0x01, 0x0a, 0x08, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x71, 0x12,
	0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x61, 0x72, 0x6b, 0x65,
	0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x12,
	0x24, 0x0a, 0x05, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e,
	0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x44, 0x74, 0x6f, 0x52, 0x05,
	0x6f, 0x72, 0x64, 0x65, 0x72, 0x12, 0x20, 0x0a, 0x03, 0x63, 0x6d, 0x64, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x0e, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x43,
	0x6d, 0x64, 0x52, 0x03, 0x63, 0x6d, 0x64, 0x22, 0x5f, 0x0a, 0x08, 0x4f, 0x72, 0x64, 0x65, 0x72,
	0x52, 0x73, 0x70, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x6d,
	0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x12, 0x29, 0x0a,
	0x05, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x67,
	0x72, 0x70, 0x63, 0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x44, 0x74,
	0x6f, 0x52, 0x05, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x22, 0x21, 0x0a, 0x09, 0x43, 0x6f, 0x6d, 0x6d,
	0x6f, 0x6e, 0x52, 0x65, 0x71, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x73, 0x67, 0x49, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6d, 0x73, 0x67, 0x49, 0x64, 0x22, 0x35, 0x0a, 0x09, 0x43,
	0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x52, 0x73, 0x70, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d,
	0x73, 0x67, 0x22, 0x3d, 0x0a, 0x0b, 0x42, 0x61, 0x74, 0x63, 0x68, 0x47, 0x65, 0x74, 0x52, 0x65,
	0x71, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x61, 0x72,
	0x6b, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6d, 0x61, 0x72, 0x6b, 0x65,
	0x74, 0x22, 0x65, 0x0a, 0x0b, 0x42, 0x61, 0x74, 0x63, 0x68, 0x47, 0x65, 0x74, 0x52, 0x73, 0x70,
	0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x12, 0x2c, 0x0a, 0x09, 0x6f, 0x72,
	0x64, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e,
	0x67, 0x72, 0x70, 0x63, 0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x44, 0x74, 0x6f, 0x52, 0x09, 0x6f,
	0x72, 0x64, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x4a, 0x0a, 0x0e, 0x4d, 0x61, 0x72, 0x6b,
	0x65, 0x74, 0x53, 0x68, 0x61, 0x72, 0x64, 0x44, 0x74, 0x6f, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x68,
	0x61, 0x72, 0x64, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x68, 0x61,
	0x72, 0x64, 0x49, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x4c, 0x69,
	0x73, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0a, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74,
	0x4c, 0x69, 0x73, 0x74, 0x22, 0x56, 0x0a, 0x0c, 0x53, 0x68, 0x61, 0x72, 0x64, 0x4c, 0x69, 0x73,
	0x74, 0x52, 0x73, 0x70, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x10, 0x0a, 0x03,
	0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x12, 0x1c,
	0x0a, 0x09, 0x73, 0x68, 0x61, 0x72, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x03, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x09, 0x73, 0x68, 0x61, 0x72, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x83, 0x01, 0x0a,
	0x08, 0x53, 0x68, 0x61, 0x72, 0x64, 0x52, 0x65, 0x71, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x68, 0x61,
	0x72, 0x64, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x68, 0x61, 0x72,
	0x64, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x70, 0x70, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x61, 0x70, 0x70, 0x49, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x70, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x6f, 0x72,
	0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x23, 0x0a,
	0x04, 0x72, 0x6f, 0x6c, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0f, 0x2e, 0x67, 0x72,
	0x70, 0x63, 0x2e, 0x53, 0x68, 0x61, 0x72, 0x64, 0x52, 0x6f, 0x6c, 0x65, 0x52, 0x04, 0x72, 0x6f,
	0x6c, 0x65, 0x22, 0x6e, 0x0a, 0x0c, 0x4c, 0x6f, 0x63, 0x6b, 0x53, 0x68, 0x61, 0x72, 0x64, 0x52,
	0x73, 0x70, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73,
	0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x12, 0x34, 0x0a, 0x0a,
	0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x14, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x4d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x53, 0x68,
	0x61, 0x72, 0x64, 0x44, 0x74, 0x6f, 0x52, 0x0a, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x4c, 0x69,
	0x73, 0x74, 0x22, 0x9f, 0x01, 0x0a, 0x0c, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x6f, 0x72,
	0x44, 0x74, 0x6f, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x68, 0x61, 0x72, 0x64, 0x49, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x68, 0x61, 0x72, 0x64, 0x49, 0x64, 0x12, 0x14, 0x0a,
	0x05, 0x61, 0x70, 0x70, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x61, 0x70,
	0x70, 0x49, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x69, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12,
	0x23, 0x0a, 0x04, 0x72, 0x6f, 0x6c, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0f, 0x2e,
	0x67, 0x72, 0x70, 0x63, 0x2e, 0x53, 0x68, 0x61, 0x72, 0x64, 0x52, 0x6f, 0x6c, 0x65, 0x52, 0x04,
	0x72, 0x6f, 0x6c, 0x65, 0x22, 0x76, 0x0a, 0x10, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x6f, 0x6e, 0x6e,
	0x65, 0x63, 0x74, 0x6f, 0x72, 0x52, 0x73, 0x70, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d,
	0x73, 0x67, 0x12, 0x38, 0x0a, 0x0d, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x4c,
	0x69, 0x73, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x67, 0x72, 0x70, 0x63,
	0x2e, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x44, 0x74, 0x6f, 0x52, 0x0d, 0x63,
	0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x2a, 0x64, 0x0a, 0x09,
	0x4f, 0x72, 0x64, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0a, 0x0a, 0x06, 0x4f, 0x54, 0x5f,
	0x47, 0x54, 0x43, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x4f, 0x54, 0x5f, 0x49, 0x4f, 0x43, 0x10,
	0x01, 0x12, 0x11, 0x0a, 0x0d, 0x4f, 0x54, 0x5f, 0x49, 0x4f, 0x43, 0x5f, 0x42, 0x55, 0x44, 0x47,
	0x45, 0x54, 0x10, 0x02, 0x12, 0x0a, 0x0a, 0x06, 0x4f, 0x54, 0x5f, 0x46, 0x4f, 0x4b, 0x10, 0x03,
	0x12, 0x11, 0x0a, 0x0d, 0x4f, 0x54, 0x5f, 0x46, 0x4f, 0x4b, 0x5f, 0x42, 0x55, 0x44, 0x47, 0x45,
	0x54, 0x10, 0x04, 0x12, 0x0d, 0x0a, 0x09, 0x4f, 0x54, 0x5f, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57,
	0x10, 0x05, 0x2a, 0x33, 0x0a, 0x08, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x53, 0x69, 0x64, 0x12, 0x0c,
	0x0a, 0x08, 0x53, 0x44, 0x5f, 0x4f, 0x46, 0x46, 0x45, 0x52, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06,
	0x53, 0x44, 0x5f, 0x42, 0x49, 0x44, 0x10, 0x01, 0x12, 0x0d, 0x0a, 0x09, 0x53, 0x44, 0x5f, 0x55,
	0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x10, 0x02, 0x2a, 0x57, 0x0a, 0x08, 0x4f, 0x72, 0x64, 0x65, 0x72,
	0x43, 0x6d, 0x64, 0x12, 0x0d, 0x0a, 0x09, 0x43, 0x4d, 0x44, 0x5f, 0x50, 0x4c, 0x41, 0x43, 0x45,
	0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08, 0x43, 0x4d, 0x44, 0x5f, 0x4d, 0x4f, 0x56, 0x45, 0x10, 0x01,
	0x12, 0x0e, 0x0a, 0x0a, 0x43, 0x4d, 0x44, 0x5f, 0x43, 0x41, 0x4e, 0x43, 0x45, 0x4c, 0x10, 0x02,
	0x12, 0x0e, 0x0a, 0x0a, 0x43, 0x4d, 0x44, 0x5f, 0x52, 0x45, 0x44, 0x55, 0x43, 0x45, 0x10, 0x03,
	0x12, 0x0e, 0x0a, 0x0a, 0x43, 0x4d, 0x44, 0x5f, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x10, 0x04,
	0x2a, 0x68, 0x0a, 0x0b, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12,
	0x0e, 0x0a, 0x0a, 0x53, 0x54, 0x5f, 0x49, 0x4e, 0x49, 0x54, 0x49, 0x41, 0x4c, 0x10, 0x00, 0x12,
	0x0d, 0x0a, 0x09, 0x53, 0x54, 0x5f, 0x41, 0x43, 0x43, 0x45, 0x50, 0x54, 0x10, 0x01, 0x12, 0x0d,
	0x0a, 0x09, 0x53, 0x54, 0x5f, 0x52, 0x45, 0x4a, 0x45, 0x43, 0x54, 0x10, 0x02, 0x12, 0x0d, 0x0a,
	0x09, 0x53, 0x54, 0x5f, 0x43, 0x41, 0x4e, 0x43, 0x45, 0x4c, 0x10, 0x03, 0x12, 0x0d, 0x0a, 0x09,
	0x53, 0x54, 0x5f, 0x46, 0x49, 0x4e, 0x49, 0x53, 0x48, 0x10, 0x04, 0x12, 0x0d, 0x0a, 0x09, 0x53,
	0x54, 0x5f, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x10, 0x05, 0x2a, 0x2c, 0x0a, 0x09, 0x53, 0x68,
	0x61, 0x72, 0x64, 0x52, 0x6f, 0x6c, 0x65, 0x12, 0x0f, 0x0a, 0x0b, 0x52, 0x4f, 0x4c, 0x45, 0x5f,
	0x4d, 0x41, 0x52, 0x4b, 0x45, 0x54, 0x10, 0x00, 0x12, 0x0e, 0x0a, 0x0a, 0x52, 0x4f, 0x4c, 0x45,
	0x5f, 0x53, 0x54, 0x4f, 0x52, 0x45, 0x10, 0x01, 0x42, 0x07, 0x5a, 0x05, 0x2f, 0x67, 0x72, 0x70,
	0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_taoContext_proto_rawDescOnce sync.Once
	file_taoContext_proto_rawDescData = file_taoContext_proto_rawDesc
)

func file_taoContext_proto_rawDescGZIP() []byte {
	file_taoContext_proto_rawDescOnce.Do(func() {
		file_taoContext_proto_rawDescData = protoimpl.X.CompressGZIP(file_taoContext_proto_rawDescData)
	})
	return file_taoContext_proto_rawDescData
}

var file_taoContext_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_taoContext_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_taoContext_proto_goTypes = []interface{}{
	(OrderType)(0),           // 0: grpc.OrderType
	(OrderSid)(0),            // 1: grpc.OrderSid
	(OrderCmd)(0),            // 2: grpc.OrderCmd
	(OrderStatus)(0),         // 3: grpc.OrderStatus
	(ShardRole)(0),           // 4: grpc.ShardRole
	(*OrderDto)(nil),         // 5: grpc.OrderDto
	(*OrderReplyDto)(nil),    // 6: grpc.OrderReplyDto
	(*MarketDto)(nil),        // 7: grpc.MarketDto
	(*QueryReq)(nil),         // 8: grpc.QueryReq
	(*QueryRsp)(nil),         // 9: grpc.QueryRsp
	(*OrderReq)(nil),         // 10: grpc.OrderReq
	(*OrderRsp)(nil),         // 11: grpc.OrderRsp
	(*CommonReq)(nil),        // 12: grpc.CommonReq
	(*CommonRsp)(nil),        // 13: grpc.CommonRsp
	(*BatchGetReq)(nil),      // 14: grpc.BatchGetReq
	(*BatchGetRsp)(nil),      // 15: grpc.BatchGetRsp
	(*MarketShardDto)(nil),   // 16: grpc.MarketShardDto
	(*ShardListRsp)(nil),     // 17: grpc.ShardListRsp
	(*ShardReq)(nil),         // 18: grpc.ShardReq
	(*LockShardRsp)(nil),     // 19: grpc.LockShardRsp
	(*ConnectorDto)(nil),     // 20: grpc.ConnectorDto
	(*ListConnectorRsp)(nil), // 21: grpc.ListConnectorRsp
}
var file_taoContext_proto_depIdxs = []int32{
	0,  // 0: grpc.OrderDto.type:type_name -> grpc.OrderType
	1,  // 1: grpc.OrderDto.side:type_name -> grpc.OrderSid
	3,  // 2: grpc.OrderDto.status:type_name -> grpc.OrderStatus
	5,  // 3: grpc.OrderReplyDto.order:type_name -> grpc.OrderDto
	5,  // 4: grpc.QueryRsp.orderList:type_name -> grpc.OrderDto
	5,  // 5: grpc.OrderReq.order:type_name -> grpc.OrderDto
	2,  // 6: grpc.OrderReq.cmd:type_name -> grpc.OrderCmd
	6,  // 7: grpc.OrderRsp.order:type_name -> grpc.OrderReplyDto
	5,  // 8: grpc.BatchGetRsp.orderList:type_name -> grpc.OrderDto
	4,  // 9: grpc.ShardReq.role:type_name -> grpc.ShardRole
	16, // 10: grpc.LockShardRsp.marketList:type_name -> grpc.MarketShardDto
	4,  // 11: grpc.ConnectorDto.role:type_name -> grpc.ShardRole
	20, // 12: grpc.ListConnectorRsp.connectorList:type_name -> grpc.ConnectorDto
	13, // [13:13] is the sub-list for method output_type
	13, // [13:13] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_taoContext_proto_init() }
func file_taoContext_proto_init() {
	if File_taoContext_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_taoContext_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrderDto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_taoContext_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrderReplyDto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_taoContext_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MarketDto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_taoContext_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_taoContext_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_taoContext_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrderReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_taoContext_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrderRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_taoContext_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommonReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_taoContext_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommonRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_taoContext_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BatchGetReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_taoContext_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BatchGetRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_taoContext_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MarketShardDto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_taoContext_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShardListRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_taoContext_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShardReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_taoContext_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LockShardRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_taoContext_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConnectorDto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_taoContext_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListConnectorRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_taoContext_proto_rawDesc,
			NumEnums:      5,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_taoContext_proto_goTypes,
		DependencyIndexes: file_taoContext_proto_depIdxs,
		EnumInfos:         file_taoContext_proto_enumTypes,
		MessageInfos:      file_taoContext_proto_msgTypes,
	}.Build()
	File_taoContext_proto = out.File
	file_taoContext_proto_rawDesc = nil
	file_taoContext_proto_goTypes = nil
	file_taoContext_proto_depIdxs = nil
}
