// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.21.1
// source: taoMsgQ.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TaoMsgCmd int32

const (
	TaoMsgCmd_MSG_TOPIC_C     TaoMsgCmd = 0
	TaoMsgCmd_MSG_TOPIC_D     TaoMsgCmd = 1
	TaoMsgCmd_MSG_SLAVE_A     TaoMsgCmd = 2
	TaoMsgCmd_MSG_CONSUME_SYC TaoMsgCmd = 3
)

// Enum value maps for TaoMsgCmd.
var (
	TaoMsgCmd_name = map[int32]string{
		0: "MSG_TOPIC_C",
		1: "MSG_TOPIC_D",
		2: "MSG_SLAVE_A",
		3: "MSG_CONSUME_SYC",
	}
	TaoMsgCmd_value = map[string]int32{
		"MSG_TOPIC_C":     0,
		"MSG_TOPIC_D":     1,
		"MSG_SLAVE_A":     2,
		"MSG_CONSUME_SYC": 3,
	}
)

func (x TaoMsgCmd) Enum() *TaoMsgCmd {
	p := new(TaoMsgCmd)
	*p = x
	return p
}

func (x TaoMsgCmd) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaoMsgCmd) Descriptor() protoreflect.EnumDescriptor {
	return file_taoMsgQ_proto_enumTypes[0].Descriptor()
}

func (TaoMsgCmd) Type() protoreflect.EnumType {
	return &file_taoMsgQ_proto_enumTypes[0]
}

func (x TaoMsgCmd) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaoMsgCmd.Descriptor instead.
func (TaoMsgCmd) EnumDescriptor() ([]byte, []int) {
	return file_taoMsgQ_proto_rawDescGZIP(), []int{0}
}

type TaoCode int32

const (
	TaoCode_TC_OK            TaoCode = 0
	TaoCode_TC_PUB_ERR       TaoCode = 1000
	TaoCode_TC_BRK_ERR       TaoCode = 1001
	TaoCode_TC_BRK_SLAVE_ERR TaoCode = 1002
	TaoCode_TC_SUB_ERR       TaoCode = 1003
	TaoCode_TC_BRK_ROLE_ERR  TaoCode = 1004
)

// Enum value maps for TaoCode.
var (
	TaoCode_name = map[int32]string{
		0:    "TC_OK",
		1000: "TC_PUB_ERR",
		1001: "TC_BRK_ERR",
		1002: "TC_BRK_SLAVE_ERR",
		1003: "TC_SUB_ERR",
		1004: "TC_BRK_ROLE_ERR",
	}
	TaoCode_value = map[string]int32{
		"TC_OK":            0,
		"TC_PUB_ERR":       1000,
		"TC_BRK_ERR":       1001,
		"TC_BRK_SLAVE_ERR": 1002,
		"TC_SUB_ERR":       1003,
		"TC_BRK_ROLE_ERR":  1004,
	}
)

func (x TaoCode) Enum() *TaoCode {
	p := new(TaoCode)
	*p = x
	return p
}

func (x TaoCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaoCode) Descriptor() protoreflect.EnumDescriptor {
	return file_taoMsgQ_proto_enumTypes[1].Descriptor()
}

func (TaoCode) Type() protoreflect.EnumType {
	return &file_taoMsgQ_proto_enumTypes[1]
}

func (x TaoCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaoCode.Descriptor instead.
func (TaoCode) EnumDescriptor() ([]byte, []int) {
	return file_taoMsgQ_proto_rawDescGZIP(), []int{1}
}

type TaoMsgCmdReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cmd   TaoMsgCmd `protobuf:"varint,1,opt,name=cmd,proto3,enum=grpc.TaoMsgCmd" json:"cmd,omitempty"`
	CmdId string    `protobuf:"bytes,2,opt,name=cmdId,proto3" json:"cmdId,omitempty"`
	Data  []byte    `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *TaoMsgCmdReq) Reset() {
	*x = TaoMsgCmdReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_taoMsgQ_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TaoMsgCmdReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaoMsgCmdReq) ProtoMessage() {}

func (x *TaoMsgCmdReq) ProtoReflect() protoreflect.Message {
	mi := &file_taoMsgQ_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaoMsgCmdReq.ProtoReflect.Descriptor instead.
func (*TaoMsgCmdReq) Descriptor() ([]byte, []int) {
	return file_taoMsgQ_proto_rawDescGZIP(), []int{0}
}

func (x *TaoMsgCmdReq) GetCmd() TaoMsgCmd {
	if x != nil {
		return x.Cmd
	}
	return TaoMsgCmd_MSG_TOPIC_C
}

func (x *TaoMsgCmdReq) GetCmdId() string {
	if x != nil {
		return x.CmdId
	}
	return ""
}

func (x *TaoMsgCmdReq) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type TaoMsgCmdRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CmdId string `protobuf:"bytes,1,opt,name=cmdId,proto3" json:"cmdId,omitempty"`
	Code  int32  `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	Msg   string `protobuf:"bytes,3,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *TaoMsgCmdRsp) Reset() {
	*x = TaoMsgCmdRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_taoMsgQ_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TaoMsgCmdRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaoMsgCmdRsp) ProtoMessage() {}

func (x *TaoMsgCmdRsp) ProtoReflect() protoreflect.Message {
	mi := &file_taoMsgQ_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaoMsgCmdRsp.ProtoReflect.Descriptor instead.
func (*TaoMsgCmdRsp) Descriptor() ([]byte, []int) {
	return file_taoMsgQ_proto_rawDescGZIP(), []int{1}
}

func (x *TaoMsgCmdRsp) GetCmdId() string {
	if x != nil {
		return x.CmdId
	}
	return ""
}

func (x *TaoMsgCmdRsp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *TaoMsgCmdRsp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type TaoMsgReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MsgId     string            `protobuf:"bytes,1,opt,name=msgId,proto3" json:"msgId,omitempty"`
	Topic     string            `protobuf:"bytes,2,opt,name=topic,proto3" json:"topic,omitempty"`
	PubId     string            `protobuf:"bytes,3,opt,name=pubId,proto3" json:"pubId,omitempty"`
	Data      []byte            `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	TimeStamp int64             `protobuf:"varint,5,opt,name=timeStamp,proto3" json:"timeStamp,omitempty"`
	BrkId     int64             `protobuf:"varint,6,opt,name=brkId,proto3" json:"brkId,omitempty"`
	Headers   map[string][]byte `protobuf:"bytes,7,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *TaoMsgReq) Reset() {
	*x = TaoMsgReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_taoMsgQ_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TaoMsgReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaoMsgReq) ProtoMessage() {}

func (x *TaoMsgReq) ProtoReflect() protoreflect.Message {
	mi := &file_taoMsgQ_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaoMsgReq.ProtoReflect.Descriptor instead.
func (*TaoMsgReq) Descriptor() ([]byte, []int) {
	return file_taoMsgQ_proto_rawDescGZIP(), []int{2}
}

func (x *TaoMsgReq) GetMsgId() string {
	if x != nil {
		return x.MsgId
	}
	return ""
}

func (x *TaoMsgReq) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *TaoMsgReq) GetPubId() string {
	if x != nil {
		return x.PubId
	}
	return ""
}

func (x *TaoMsgReq) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *TaoMsgReq) GetTimeStamp() int64 {
	if x != nil {
		return x.TimeStamp
	}
	return 0
}

func (x *TaoMsgReq) GetBrkId() int64 {
	if x != nil {
		return x.BrkId
	}
	return 0
}

func (x *TaoMsgReq) GetHeaders() map[string][]byte {
	if x != nil {
		return x.Headers
	}
	return nil
}

type TaoMsgRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MsgId string `protobuf:"bytes,1,opt,name=msgId,proto3" json:"msgId,omitempty"`
	BrkId int64  `protobuf:"varint,2,opt,name=brkId,proto3" json:"brkId,omitempty"`
	Code  int32  `protobuf:"varint,3,opt,name=code,proto3" json:"code,omitempty"`
	Msg   string `protobuf:"bytes,4,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *TaoMsgRsp) Reset() {
	*x = TaoMsgRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_taoMsgQ_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TaoMsgRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaoMsgRsp) ProtoMessage() {}

func (x *TaoMsgRsp) ProtoReflect() protoreflect.Message {
	mi := &file_taoMsgQ_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaoMsgRsp.ProtoReflect.Descriptor instead.
func (*TaoMsgRsp) Descriptor() ([]byte, []int) {
	return file_taoMsgQ_proto_rawDescGZIP(), []int{3}
}

func (x *TaoMsgRsp) GetMsgId() string {
	if x != nil {
		return x.MsgId
	}
	return ""
}

func (x *TaoMsgRsp) GetBrkId() int64 {
	if x != nil {
		return x.BrkId
	}
	return 0
}

func (x *TaoMsgRsp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *TaoMsgRsp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type TaoSubReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Topic   string `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	GroupId string `protobuf:"bytes,2,opt,name=groupId,proto3" json:"groupId,omitempty"`
	SubId   string `protobuf:"bytes,3,opt,name=subId,proto3" json:"subId,omitempty"`
}

func (x *TaoSubReq) Reset() {
	*x = TaoSubReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_taoMsgQ_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TaoSubReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaoSubReq) ProtoMessage() {}

func (x *TaoSubReq) ProtoReflect() protoreflect.Message {
	mi := &file_taoMsgQ_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaoSubReq.ProtoReflect.Descriptor instead.
func (*TaoSubReq) Descriptor() ([]byte, []int) {
	return file_taoMsgQ_proto_rawDescGZIP(), []int{4}
}

func (x *TaoSubReq) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *TaoSubReq) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *TaoSubReq) GetSubId() string {
	if x != nil {
		return x.SubId
	}
	return ""
}

type TaoMsgConAdr struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Port  int32  `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	Ip    string `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	BrkId string `protobuf:"bytes,3,opt,name=brkId,proto3" json:"brkId,omitempty"`
}

func (x *TaoMsgConAdr) Reset() {
	*x = TaoMsgConAdr{}
	if protoimpl.UnsafeEnabled {
		mi := &file_taoMsgQ_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TaoMsgConAdr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaoMsgConAdr) ProtoMessage() {}

func (x *TaoMsgConAdr) ProtoReflect() protoreflect.Message {
	mi := &file_taoMsgQ_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaoMsgConAdr.ProtoReflect.Descriptor instead.
func (*TaoMsgConAdr) Descriptor() ([]byte, []int) {
	return file_taoMsgQ_proto_rawDescGZIP(), []int{5}
}

func (x *TaoMsgConAdr) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *TaoMsgConAdr) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *TaoMsgConAdr) GetBrkId() string {
	if x != nil {
		return x.BrkId
	}
	return ""
}

type TaoMsgConsumeInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Topic   string `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	GroupId string `protobuf:"bytes,2,opt,name=groupId,proto3" json:"groupId,omitempty"`
	Offset  int64  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	BrkId   int64  `protobuf:"varint,4,opt,name=brkId,proto3" json:"brkId,omitempty"`
}

func (x *TaoMsgConsumeInfo) Reset() {
	*x = TaoMsgConsumeInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_taoMsgQ_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TaoMsgConsumeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaoMsgConsumeInfo) ProtoMessage() {}

func (x *TaoMsgConsumeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_taoMsgQ_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaoMsgConsumeInfo.ProtoReflect.Descriptor instead.
func (*TaoMsgConsumeInfo) Descriptor() ([]byte, []int) {
	return file_taoMsgQ_proto_rawDescGZIP(), []int{6}
}

func (x *TaoMsgConsumeInfo) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *TaoMsgConsumeInfo) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *TaoMsgConsumeInfo) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *TaoMsgConsumeInfo) GetBrkId() int64 {
	if x != nil {
		return x.BrkId
	}
	return 0
}

var File_taoMsgQ_proto protoreflect.FileDescriptor

var file_taoMsgQ_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x74, 0x61, 0x6f, 0x4d, 0x73, 0x67, 0x51, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x04, 0x67, 0x72, 0x70, 0x63, 0x22, 0x5b, 0x0a, 0x0c, 0x54, 0x61, 0x6f, 0x4d, 0x73, 0x67, 0x43,
	0x6d, 0x64, 0x52, 0x65, 0x71, 0x12, 0x21, 0x0a, 0x03, 0x63, 0x6d, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x0f, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x54, 0x61, 0x6f, 0x4d, 0x73, 0x67,
	0x43, 0x6d, 0x64, 0x52, 0x03, 0x63, 0x6d, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6d, 0x64, 0x49,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x63, 0x6d, 0x64, 0x49, 0x64, 0x12, 0x12,
	0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x22, 0x4a, 0x0a, 0x0c, 0x54, 0x61, 0x6f, 0x4d, 0x73, 0x67, 0x43, 0x6d, 0x64, 0x52,
	0x73, 0x70, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6d, 0x64, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x63, 0x6d, 0x64, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03,
	0x6d, 0x73, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x89,
	0x02, 0x0a, 0x09, 0x54, 0x61, 0x6f, 0x4d, 0x73, 0x67, 0x52, 0x65, 0x71, 0x12, 0x14, 0x0a, 0x05,
	0x6d, 0x73, 0x67, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6d, 0x73, 0x67,
	0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x70, 0x69, 0x63, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x74, 0x6f, 0x70, 0x69, 0x63, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x75, 0x62, 0x49,
	0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x70, 0x75, 0x62, 0x49, 0x64, 0x12, 0x12,
	0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x6d, 0x70, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x6d, 0x70,
	0x12, 0x14, 0x0a, 0x05, 0x62, 0x72, 0x6b, 0x49, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x05, 0x62, 0x72, 0x6b, 0x49, 0x64, 0x12, 0x36, 0x0a, 0x07, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72,
	0x73, 0x18, 0x07, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x54,
	0x61, 0x6f, 0x4d, 0x73, 0x67, 0x52, 0x65, 0x71, 0x2e, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73,
	0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x07, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73, 0x1a, 0x3a,
	0x0a, 0x0c, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10,
	0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79,
	0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x5d, 0x0a, 0x09, 0x54, 0x61,
	0x6f, 0x4d, 0x73, 0x67, 0x52, 0x73, 0x70, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x73, 0x67, 0x49, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6d, 0x73, 0x67, 0x49, 0x64, 0x12, 0x14, 0x0a,
	0x05, 0x62, 0x72, 0x6b, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x62, 0x72,
	0x6b, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x51, 0x0a, 0x09, 0x54, 0x61, 0x6f,
	0x53, 0x75, 0x62, 0x52, 0x65, 0x71, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x70, 0x69, 0x63, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x70, 0x69, 0x63, 0x12, 0x18, 0x0a, 0x07,
	0x67, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x67,
	0x72, 0x6f, 0x75, 0x70, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x75, 0x62, 0x49, 0x64, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x73, 0x75, 0x62, 0x49, 0x64, 0x22, 0x48, 0x0a, 0x0c,
	0x54, 0x61, 0x6f, 0x4d, 0x73, 0x67, 0x43, 0x6f, 0x6e, 0x41, 0x64, 0x72, 0x12, 0x12, 0x0a, 0x04,
	0x70, 0x6f, 0x72, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x70, 0x6f, 0x72, 0x74,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x70,
	0x12, 0x14, 0x0a, 0x05, 0x62, 0x72, 0x6b, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x62, 0x72, 0x6b, 0x49, 0x64, 0x22, 0x71, 0x0a, 0x11, 0x54, 0x61, 0x6f, 0x4d, 0x73, 0x67,
	0x43, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x14, 0x0a, 0x05, 0x74,
	0x6f, 0x70, 0x69, 0x63, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x70, 0x69,
	0x63, 0x12, 0x18, 0x0a, 0x07, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x6f,
	0x66, 0x66, 0x73, 0x65, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x6f, 0x66, 0x66,
	0x73, 0x65, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x62, 0x72, 0x6b, 0x49, 0x64, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x05, 0x62, 0x72, 0x6b, 0x49, 0x64, 0x2a, 0x53, 0x0a, 0x09, 0x54, 0x61, 0x6f,
	0x4d, 0x73, 0x67, 0x43, 0x6d, 0x64, 0x12, 0x0f, 0x0a, 0x0b, 0x4d, 0x53, 0x47, 0x5f, 0x54, 0x4f,
	0x50, 0x49, 0x43, 0x5f, 0x43, 0x10, 0x00, 0x12, 0x0f, 0x0a, 0x0b, 0x4d, 0x53, 0x47, 0x5f, 0x54,
	0x4f, 0x50, 0x49, 0x43, 0x5f, 0x44, 0x10, 0x01, 0x12, 0x0f, 0x0a, 0x0b, 0x4d, 0x53, 0x47, 0x5f,
	0x53, 0x4c, 0x41, 0x56, 0x45, 0x5f, 0x41, 0x10, 0x02, 0x12, 0x13, 0x0a, 0x0f, 0x4d, 0x53, 0x47,
	0x5f, 0x43, 0x4f, 0x4e, 0x53, 0x55, 0x4d, 0x45, 0x5f, 0x53, 0x59, 0x43, 0x10, 0x03, 0x2a, 0x74,
	0x0a, 0x07, 0x54, 0x61, 0x6f, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x09, 0x0a, 0x05, 0x54, 0x43, 0x5f,
	0x4f, 0x4b, 0x10, 0x00, 0x12, 0x0f, 0x0a, 0x0a, 0x54, 0x43, 0x5f, 0x50, 0x55, 0x42, 0x5f, 0x45,
	0x52, 0x52, 0x10, 0xe8, 0x07, 0x12, 0x0f, 0x0a, 0x0a, 0x54, 0x43, 0x5f, 0x42, 0x52, 0x4b, 0x5f,
	0x45, 0x52, 0x52, 0x10, 0xe9, 0x07, 0x12, 0x15, 0x0a, 0x10, 0x54, 0x43, 0x5f, 0x42, 0x52, 0x4b,
	0x5f, 0x53, 0x4c, 0x41, 0x56, 0x45, 0x5f, 0x45, 0x52, 0x52, 0x10, 0xea, 0x07, 0x12, 0x0f, 0x0a,
	0x0a, 0x54, 0x43, 0x5f, 0x53, 0x55, 0x42, 0x5f, 0x45, 0x52, 0x52, 0x10, 0xeb, 0x07, 0x12, 0x14,
	0x0a, 0x0f, 0x54, 0x43, 0x5f, 0x42, 0x52, 0x4b, 0x5f, 0x52, 0x4f, 0x4c, 0x45, 0x5f, 0x45, 0x52,
	0x52, 0x10, 0xec, 0x07, 0x32, 0xc0, 0x01, 0x0a, 0x09, 0x54, 0x61, 0x6f, 0x42, 0x72, 0x6f, 0x6b,
	0x65, 0x72, 0x12, 0x2f, 0x0a, 0x03, 0x63, 0x6d, 0x64, 0x12, 0x12, 0x2e, 0x67, 0x72, 0x70, 0x63,
	0x2e, 0x54, 0x61, 0x6f, 0x4d, 0x73, 0x67, 0x43, 0x6d, 0x64, 0x52, 0x65, 0x71, 0x1a, 0x12, 0x2e,
	0x67, 0x72, 0x70, 0x63, 0x2e, 0x54, 0x61, 0x6f, 0x4d, 0x73, 0x67, 0x43, 0x6d, 0x64, 0x52, 0x73,
	0x70, 0x22, 0x00, 0x12, 0x29, 0x0a, 0x03, 0x70, 0x75, 0x62, 0x12, 0x0f, 0x2e, 0x67, 0x72, 0x70,
	0x63, 0x2e, 0x54, 0x61, 0x6f, 0x4d, 0x73, 0x67, 0x52, 0x65, 0x71, 0x1a, 0x0f, 0x2e, 0x67, 0x72,
	0x70, 0x63, 0x2e, 0x54, 0x61, 0x6f, 0x4d, 0x73, 0x67, 0x52, 0x73, 0x70, 0x22, 0x00, 0x12, 0x2a,
	0x0a, 0x04, 0x73, 0x79, 0x6e, 0x63, 0x12, 0x0f, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x54, 0x61,
	0x6f, 0x4d, 0x73, 0x67, 0x52, 0x65, 0x71, 0x1a, 0x0f, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x54,
	0x61, 0x6f, 0x4d, 0x73, 0x67, 0x52, 0x73, 0x70, 0x22, 0x00, 0x12, 0x2b, 0x0a, 0x03, 0x73, 0x75,
	0x62, 0x12, 0x0f, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x54, 0x61, 0x6f, 0x53, 0x75, 0x62, 0x52,
	0x65, 0x71, 0x1a, 0x0f, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x54, 0x61, 0x6f, 0x4d, 0x73, 0x67,
	0x52, 0x65, 0x71, 0x22, 0x00, 0x30, 0x01, 0x42, 0x20, 0x0a, 0x15, 0x74, 0x61, 0x6f, 0x2e, 0x65,
	0x78, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x67, 0x72, 0x70, 0x63,
	0x50, 0x01, 0x5a, 0x05, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_taoMsgQ_proto_rawDescOnce sync.Once
	file_taoMsgQ_proto_rawDescData = file_taoMsgQ_proto_rawDesc
)

func file_taoMsgQ_proto_rawDescGZIP() []byte {
	file_taoMsgQ_proto_rawDescOnce.Do(func() {
		file_taoMsgQ_proto_rawDescData = protoimpl.X.CompressGZIP(file_taoMsgQ_proto_rawDescData)
	})
	return file_taoMsgQ_proto_rawDescData
}

var file_taoMsgQ_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_taoMsgQ_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_taoMsgQ_proto_goTypes = []interface{}{
	(TaoMsgCmd)(0),            // 0: grpc.TaoMsgCmd
	(TaoCode)(0),              // 1: grpc.TaoCode
	(*TaoMsgCmdReq)(nil),      // 2: grpc.TaoMsgCmdReq
	(*TaoMsgCmdRsp)(nil),      // 3: grpc.TaoMsgCmdRsp
	(*TaoMsgReq)(nil),         // 4: grpc.TaoMsgReq
	(*TaoMsgRsp)(nil),         // 5: grpc.TaoMsgRsp
	(*TaoSubReq)(nil),         // 6: grpc.TaoSubReq
	(*TaoMsgConAdr)(nil),      // 7: grpc.TaoMsgConAdr
	(*TaoMsgConsumeInfo)(nil), // 8: grpc.TaoMsgConsumeInfo
	nil,                       // 9: grpc.TaoMsgReq.HeadersEntry
}
var file_taoMsgQ_proto_depIdxs = []int32{
	0, // 0: grpc.TaoMsgCmdReq.cmd:type_name -> grpc.TaoMsgCmd
	9, // 1: grpc.TaoMsgReq.headers:type_name -> grpc.TaoMsgReq.HeadersEntry
	2, // 2: grpc.TaoBroker.cmd:input_type -> grpc.TaoMsgCmdReq
	4, // 3: grpc.TaoBroker.pub:input_type -> grpc.TaoMsgReq
	4, // 4: grpc.TaoBroker.sync:input_type -> grpc.TaoMsgReq
	6, // 5: grpc.TaoBroker.sub:input_type -> grpc.TaoSubReq
	3, // 6: grpc.TaoBroker.cmd:output_type -> grpc.TaoMsgCmdRsp
	5, // 7: grpc.TaoBroker.pub:output_type -> grpc.TaoMsgRsp
	5, // 8: grpc.TaoBroker.sync:output_type -> grpc.TaoMsgRsp
	4, // 9: grpc.TaoBroker.sub:output_type -> grpc.TaoMsgReq
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_taoMsgQ_proto_init() }
func file_taoMsgQ_proto_init() {
	if File_taoMsgQ_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_taoMsgQ_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TaoMsgCmdReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_taoMsgQ_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TaoMsgCmdRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_taoMsgQ_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TaoMsgReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_taoMsgQ_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TaoMsgRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_taoMsgQ_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TaoSubReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_taoMsgQ_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TaoMsgConAdr); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_taoMsgQ_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TaoMsgConsumeInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_taoMsgQ_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_taoMsgQ_proto_goTypes,
		DependencyIndexes: file_taoMsgQ_proto_depIdxs,
		EnumInfos:         file_taoMsgQ_proto_enumTypes,
		MessageInfos:      file_taoMsgQ_proto_msgTypes,
	}.Build()
	File_taoMsgQ_proto = out.File
	file_taoMsgQ_proto_rawDesc = nil
	file_taoMsgQ_proto_goTypes = nil
	file_taoMsgQ_proto_depIdxs = nil
}
