create DATABASE taoexchangedb;

create table tao_lock(
	id int generated by default as identity,
	shardId varchar(64) primary key,
	appId varchar(32) NOT NULL,
	appIp varchar(64) NOT NULL,
	appRole varchar(16) NOT NULL,
	appPort int NOT NULL,
	appStatus int NOT NULL,
	lockTime timestamp NOT NULL
);

create table tao_shard_market(
	id int generated by default as identity,
	marketId varchar(64) primary key,
	shardId varchar(64) NOT NULL,
	createTime timestamp NOT NULL
);

create table tao_market(
	id int generated by default as identity,
	market varchar(64) primary key,
	base   varchar(16) NOT NULL,
	pair   varchar(16) NOT NULL,
	marketStatus int NOT NULL,
	basePrec int NOT NULL,
	pairPrec int NOT NULL,
	feePrec int NOT NULL,
	minAmount bigint NOT NULL,
	minBase bigint NOT NULL,
	creatTime timestamp NOT NULL
);

create table tao_order(
	id bigint generated by default as identity primary key,
	ordId varchar(64) NOT NULL,
	ordType int NOT NULL,
	ordSide int NOT NULL,
	ordStatus int NOT NULL,
	ordVer int NOT NULL,
    ordMarket varchar(64) NOT NULL,
	ordMinBase bigint NOT NULL,
	ordPrice bigint NOT NULL,
	ordReserveBidPrice bigint NOT NULL,
	ordAmount bigint NOT NULL,
	ordFilled bigint NOT NULL,
	ordTakerFee bigint NOT NULL,
	ordMakerFee bigint NOT NULL,
	ordFee bigint NOT NULL,
	ordUserId varchar(64) NOT NULL,
	ordSource varchar(16) NOT NULL,
	ordCreateTime timestamp NOT NULL,
	ordUpdateTime timestamp NOT NULL
);

create index lock_time_idx ON tao_lock(lockTime);
create index shard_id_idx ON tao_shard_market(shardId);

create index ord_market_idx ON tao_order(ordMarket);
create index ord_user_id_idx ON tao_order(ordUserId);
create index ord_update_time_idx ON tao_order(ordUpdateTime);
create unique index ord_id_uq ON tao_order(ordId);